### ISSUE TITLE
Evaluate: meta-llama/Llama-2-13b-chat-hf

### ISSUE THREAD

**Issue by ggbetz** [logikon-ai/cot-eval#19]
Check:

* [x] The model has not been evaluated yet and doesn't show up on the [CoT Leaderboard](https://huggingface.co/spaces/logikon/open_cot_leaderboard).
* [x] There is no evaluation request issue for the model in the repo.
* [x] The parameters below have been adapted and shall be used.

Parameters:

```console
NEXT_MODEL_PATH=meta-llama/Llama-2-13b-chat-hf
NEXT_MODEL_REVISION=main
NEXT_MODEL_PRECISION=float16
MAX_LENGTH=2048 
GPU_MEMORY_UTILIZATION=0.8
VLLM_SWAP_SPACE=32
```
